import type * as V0VRM from '../types/types-vrm-0.0';
import type * as V1VRMSchema from '../types/types-vrmc-vrm-1.0';
import { VRMExpressionNameType } from './vrm-expression/vrm-expression';
import { VRMHumanBoneName } from './vrm-humanoid/vrm-humanoid';

export const VRMHumanBoneList: VRMHumanBoneName[] = [
  'hips',
  'spine',
  'chest',
  'upperChest',
  'neck',

  'head',
  'leftEye',
  'rightEye',
  'jaw',

  'leftUpperLeg',
  'leftLowerLeg',
  'leftFoot',
  'leftToes',

  'rightUpperLeg',
  'rightLowerLeg',
  'rightFoot',
  'rightToes',

  'leftShoulder',
  'leftUpperArm',
  'leftLowerArm',
  'leftHand',

  'rightShoulder',
  'rightUpperArm',
  'rightLowerArm',
  'rightHand',

  'leftThumbMetacarpal',
  'leftThumbProximal',
  'leftThumbDistal',
  'leftIndexProximal',
  'leftIndexIntermediate',
  'leftIndexDistal',
  'leftMiddleProximal',
  'leftMiddleIntermediate',
  'leftMiddleDistal',
  'leftRingProximal',
  'leftRingIntermediate',
  'leftRingDistal',
  'leftLittleProximal',
  'leftLittleIntermediate',
  'leftLittleDistal',

  'rightThumbMetacarpal',
  'rightThumbProximal',
  'rightThumbDistal',
  'rightIndexProximal',
  'rightIndexIntermediate',
  'rightIndexDistal',
  'rightMiddleProximal',
  'rightMiddleIntermediate',
  'rightMiddleDistal',
  'rightRingProximal',
  'rightRingIntermediate',
  'rightRingDistal',
  'rightLittleProximal',
  'rightLittleIntermediate',
  'rightLittleDistal',
];

export const VRMHumanBoneParentMap: { [bone in VRMHumanBoneName]: VRMHumanBoneName | null } = {
  hips: null,
  spine: 'hips',
  chest: 'spine',
  upperChest: 'chest',
  neck: 'upperChest',

  head: 'neck',
  leftEye: 'head',
  rightEye: 'head',
  jaw: 'head',
  leftUpperLeg: 'hips',
  leftLowerLeg: 'leftUpperLeg',
  leftFoot: 'leftLowerLeg',
  leftToes: 'leftFoot',
  rightUpperLeg: 'hips',
  rightLowerLeg: 'rightUpperLeg',
  rightFoot: 'rightLowerLeg',
  rightToes: 'rightFoot',
  leftShoulder: 'upperChest',
  leftUpperArm: 'leftShoulder',
  leftLowerArm: 'leftUpperArm',
  leftHand: 'leftLowerArm',
  rightShoulder: 'upperChest',
  rightUpperArm: 'rightShoulder',
  rightLowerArm: 'rightUpperArm',
  rightHand: 'rightLowerArm',

  leftThumbMetacarpal: 'leftHand',
  leftThumbProximal: 'leftThumbMetacarpal',
  leftThumbDistal: 'leftThumbProximal',
  leftIndexProximal: 'leftHand',
  leftIndexIntermediate: 'leftIndexProximal',
  leftIndexDistal: 'leftIndexIntermediate',
  leftMiddleProximal: 'leftHand',
  leftMiddleIntermediate: 'leftMiddleProximal',
  leftMiddleDistal: 'leftMiddleIntermediate',
  leftRingProximal: 'leftHand',
  leftRingIntermediate: 'leftRingProximal',
  leftRingDistal: 'leftRingIntermediate',
  leftLittleProximal: 'leftHand',
  leftLittleIntermediate: 'leftLittleProximal',
  leftLittleDistal: 'leftLittleIntermediate',

  rightThumbMetacarpal: 'rightHand',
  rightThumbProximal: 'rightThumbMetacarpal',
  rightThumbDistal: 'rightThumbProximal',
  rightIndexProximal: 'rightHand',
  rightIndexIntermediate: 'rightIndexProximal',
  rightIndexDistal: 'rightIndexIntermediate',
  rightMiddleProximal: 'rightHand',
  rightMiddleIntermediate: 'rightMiddleProximal',
  rightMiddleDistal: 'rightMiddleIntermediate',
  rightRingProximal: 'rightHand',
  rightRingIntermediate: 'rightRingProximal',
  rightRingDistal: 'rightRingIntermediate',
  rightLittleProximal: 'rightHand',
  rightLittleIntermediate: 'rightLittleProximal',
  rightLittleDistal: 'rightLittleIntermediate',
};

export const VRMRigMap: { [key: string]: VRMHumanBoneName } = {
  hips: 'hips',
  spine: 'spine',
  chest: 'chest',
  upperChest: 'upperChest',
  neck: 'neck',
  head: 'head',
  leftEye: 'leftEye',
  leftShoulder: 'leftShoulder',
  leftUpperArm: 'leftUpperArm',
  leftLowerArm: 'leftLowerArm',
  leftHand: 'leftHand',
  leftUpperLeg: 'leftUpperLeg',
  leftLowerLeg: 'leftLowerLeg',
  leftFoot: 'leftFoot',
  leftToes: 'leftToes',

  leftThumbMetacarpal: 'leftThumbMetacarpal',
  leftThumbProximal: 'leftThumbProximal',
  leftThumbDistal: 'leftThumbDistal',
  leftIndexProximal: 'leftIndexProximal',
  leftIndexIntermediate: 'leftIndexIntermediate',
  leftIndexDistal: 'leftIndexDistal',
  leftMiddleProximal: 'leftMiddleProximal',
  leftMiddleIntermediate: 'leftMiddleIntermediate',
  leftMiddleDistal: 'leftMiddleDistal',
  leftRingProximal: 'leftRingProximal',
  leftRingIntermediate: 'leftRingIntermediate',
  leftRingDistal: 'leftRingDistal',
  leftLittleProximal: 'leftLittleProximal',
  leftLittleIntermediate: 'leftLittleIntermediate',
  leftLittleDistal: 'leftLittleDistal',

  rightEye: 'rightEye',
  rightUpperArm: 'rightUpperArm',
  rightShoulder: 'rightShoulder',
  rightLowerArm: 'rightLowerArm',
  rightHand: 'rightHand',
  rightUpperLeg: 'rightUpperLeg',
  rightLowerLeg: 'rightLowerLeg',
  rightFoot: 'rightFoot',
  rightToes: 'rightToes',

  rightThumbMetacarpal: 'rightThumbMetacarpal',
  rightThumbProximal: 'rightThumbProximal',
  rightThumbDistal: 'rightThumbDistal',
  rightIndexProximal: 'rightIndexProximal',
  rightIndexIntermediate: 'rightIndexIntermediate',
  rightIndexDistal: 'rightIndexDistal',
  rightMiddleProximal: 'rightMiddleProximal',
  rightMiddleIntermediate: 'rightMiddleIntermediate',
  rightMiddleDistal: 'rightMiddleDistal',
  rightRingProximal: 'rightRingProximal',
  rightRingIntermediate: 'rightRingIntermediate',
  rightRingDistal: 'rightRingDistal',
  rightLittleProximal: 'rightLittleProximal',
  rightLittleIntermediate: 'rightLittleIntermediate',
  rightLittleDistal: 'rightLittleDistal',
};

/**
 * A map from old thumb bone names to new thumb bone names
 */
export const thumbBoneNameMap: { [key: string]: V1VRMSchema.HumanoidHumanBoneName | undefined } = {
  leftThumbProximal: 'leftThumbMetacarpal',
  leftThumbIntermediate: 'leftThumbProximal',
  rightThumbProximal: 'rightThumbMetacarpal',
  rightThumbIntermediate: 'rightThumbProximal',
};

export const v0v1PresetNameMap: { [v0Name in V0VRM.BlendShapePresetName]?: VRMExpressionNameType } =
  {
    a: 'aa',
    e: 'ee',
    i: 'ih',
    o: 'oh',
    u: 'ou',
    blink: 'blink',
    joy: 'happy',
    angry: 'angry',
    sorrow: 'sad',
    fun: 'relaxed',
    lookup: 'lookUp',
    lookdown: 'lookDown',
    lookleft: 'lookLeft',
    lookright: 'lookRight',
    blink_l: 'blinkLeft',
    blink_r: 'blinkRight',
    neutral: 'neutral',
  };

export const VRMExpressionPresetName = {
  Aa: 'aa',
  Ih: 'ih',
  Ou: 'ou',
  Ee: 'ee',
  Oh: 'oh',
  Blink: 'blink',
  Happy: 'happy',
  Angry: 'angry',
  Sad: 'sad',
  Relaxed: 'relaxed',
  LookUp: 'lookUp',
  Surprised: 'surprised',
  LookDown: 'lookDown',
  LookLeft: 'lookLeft',
  LookRight: 'lookRight',
  BlinkLeft: 'blinkLeft',
  BlinkRight: 'blinkRight',
  Neutral: 'neutral',
};
export type VRMExpressionPresetName =
  (typeof VRMExpressionPresetName)[keyof typeof VRMExpressionPresetName];

export const POSSIBLE_SPEC_VERSIONS = new Set(['1.0', '1.0-beta']);

export const v0ExpressionMaterialColorMap = {
  _Color: 'color',
  _EmissionColor: 'emissionColor',
  _ShadeColor: 'shadeColor',
  _RimColor: 'rimColor',
  _OutlineColor: 'outlineColor',
};

export const expressionMateriaPropertyNameMapMap = {
  isMeshStandardMaterial: {
    color: 'color',
    emissionColor: 'emissive',
  },
  isMeshBasicMaterial: {
    color: 'color',
  },
  isMToonMaterial: {
    color: 'color',
    emissionColor: 'emissive',
    outlineColor: 'outlineColorFactor',
    matcapColor: 'matcapFactor',
    rimColor: 'parametricRimColorFactor',
    shadeColor: 'shadeColorFactor',
  },
};
